name: Terraform Plan Composite Action
description: "Terraform Plan"

inputs:
  deployment_environment:
    required: true
    type: string
  checkout-ref:
    required: true
    type: string
  target:
    required: false
    type: string
    default: ""
  package-lambdas:
    required: false
    type: boolean
    default: false
  format-check:
    required: false
    type: boolean
    default: false
  upload-plan-file:
    required: false
    type: boolean
    default: false
  terraform-version:
    required: false
    type: string
    default: 1.13.4
  mentions:
    required: false
    type: string
  deployment_discord_webhook:
    required: false
    type: string
  protected-deployment:
    required: false
    type: boolean
    default: false
outputs:
  summary:
    value: ${{ steps.terraform-plan-string.outputs.summary }}
  drift-detected:
    value: ${{ steps.terraform-plan.outputs.drift-detected }}
runs:
  using: "composite"
  steps:
    - if: inputs.deployment_discord_webhook != ''
      name: Discord start notice
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ inputs.deployment_discord_webhook }}
        username: Github
        content: "[Deployment planning](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) started"
    - name: Git checkout
      id: git-checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout-ref }}
        fetch-depth: 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      id: setup-terraform
      with:
        terraform_wrapper: false
        terraform_version: ${{ inputs.terraform-version }}

    - if: inputs.format-check == 'true'
      id: format
      shell: bash
      run: terraform -chdir=./terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      shell: bash
      run: terraform -chdir=./terraform init

    - name: Terraform Validate
      id: validate
      shell: bash
      run: terraform -chdir=./terraform validate -no-color
      continue-on-error: false

    - name: Terraform Plan
      id: terraform-plan
      shell: bash
      run: |
        export exitcode=0
        if [ -n "${{ github.event.inputs.target }}" ]; then
          terraform -chdir=./terraform plan -detailed-exitcode -target=${{ github.event.inputs.target }} -out=tfplan || export exitcode=$?
        else
          terraform -chdir=./terraform plan -detailed-exitcode -out=tfplan  || export exitcode=$?
        fi

        echo "drift-detected=false" >> $GITHUB_OUTPUT

        if [ $exitcode -eq 2 ]; then
          echo "drift-detected=true" >> $GITHUB_OUTPUT 
          exit 0
        elif [ $exitcode -eq 1 ]; then
          echo Terraform Plan Failed!
          exit 1
        else 
          exit 0
        fi

      continue-on-error: false

    - if: ${{ inputs.upload-plan-file == 'true' }}
      name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: terraform/tfplan

    - if: inputs.package-lambdas == 'true'
      name: Upload Packaged Lambdas
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: "terraform/*.zip"

    - name: Create String Output
      id: terraform-plan-string
      shell: bash
      run: |
        TERRAFORM_PLAN=$(terraform -chdir=terraform show -no-color tfplan)

        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
        echo "## Terraform Plan Output for ${{ inputs.deployment_environment }}" >> $GITHUB_OUTPUT
        echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo '```terraform' >> $GITHUB_OUTPUT
        echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo "</details>" >> $GITHUB_OUTPUT
        echo "${{ inputs.mentions }}" >> $GITHUB_OUTPUT
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Publish Terraform Plan to Task Summary
      shell: bash
      env:
        SUMMARY: ${{ steps.terraform-plan-string.outputs.summary }}
      run: |
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

    - if: inputs.deployment_discord_webhook != ''
      name: Discord start notice
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ inputs.deployment_discord_webhook }}
        username: Github
        content: "[Deployment](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) planning finished with ${{ job.status}}"

    - if: inputs.protected-deployment == "true" && inputs.deployment_discord_webhook != '' && success()
      name: Discord approval request notice
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ inputs.deployment_discord_webhook }}
        username: Github
        content: "Please review the [deployment for approval](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for approval"
